// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicHomeSectionCountdown } from "./plasmic/copy_of_halcyon_studios/PlasmicHomeSectionCountdown";

function HomeSectionCountdown_(props, ref) {
  return (
    <PlasmicHomeSectionCountdown
      root={{ ref }}
      {...props}
      registrationLink={{
        props: {
          onClick: (e) => {
            e.preventDefault(); // Prevent the default link behavior
            window.location.href = 'https://www.halcyonstudio.us/account/';
          }
        }
      }}
    />
  );
}

const HomeSectionCountdown = React.forwardRef(HomeSectionCountdown_);

export default HomeSectionCountdown;
