// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2p9VhVhxAWhB5Nusx9QUQ2
// Component: IiQiNRBehBFl
import * as React from "react";
import { useRouter } from "next/router";
import {
  Stack as Stack__,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  useCurrentUser,
  usePlasmicTranslator
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 2p9VhVhxAWhB5Nusx9QUQ2/projectcss
import sty from "./PlasmicContainerTermsOfService.module.css"; // plasmic-import: IiQiNRBehBFl/css

createPlasmicElementProxy;

export const PlasmicContainerTermsOfService__VariantProps = new Array();

export const PlasmicContainerTermsOfService__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicContainerTermsOfService__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $translator = usePlasmicTranslator?.();
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root
      )}
    >
      <section
        data-plasmic-name={"section"}
        data-plasmic-override={overrides.section}
        className={classNames(projectcss.all, sty.section)}
      >
        <Stack__
          as={"div"}
          data-plasmic-name={"introduction"}
          data-plasmic-override={overrides.introduction}
          hasGap={true}
          className={classNames(projectcss.all, sty.introduction)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__oss5N
            )}
          >
            <Trans__>{"Introduction"}</Trans__>
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__dLisA
            )}
          >
            <Trans__>
              {
                'Welcome to Halcyon Studios! These Terms of Service ("Terms") govern your use of our website located at HalcyonStudio.us (the "Site") and all related services provided by us. By accessing or using the Site, you agree to be bound by these Terms and our Privacy Policy.'
              }
            </Trans__>
          </div>
        </Stack__>
        <Stack__
          as={"div"}
          data-plasmic-name={"definitions"}
          data-plasmic-override={overrides.definitions}
          hasGap={true}
          className={classNames(projectcss.all, sty.definitions)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__l6Bbn
            )}
          >
            <Trans__>{"Definitions"}</Trans__>
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__qQ0D
            )}
          >
            <Trans__>
              {
                'Throughout these Terms, the words "we," "us," and "our" refer to Halcyon Studios, and "you" refers to any user of the Site.'
              }
            </Trans__>
          </div>
        </Stack__>
        <Stack__
          as={"div"}
          data-plasmic-name={"useOfSite"}
          data-plasmic-override={overrides.useOfSite}
          hasGap={true}
          className={classNames(projectcss.all, sty.useOfSite)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__dsJe9
            )}
          >
            <Trans__>{"Use of the Site"}</Trans__>
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__ghri6
            )}
          >
            <Trans__>
              {
                "You agree to use the Site only for lawful purposes and in a way that does not infringe upon the rights of others or inhibit their use and enjoyment of the Site. You are solely responsible for all content you post on the Site."
              }
            </Trans__>
          </div>
        </Stack__>
        <Stack__
          as={"div"}
          data-plasmic-name={"memberships"}
          data-plasmic-override={overrides.memberships}
          hasGap={true}
          className={classNames(projectcss.all, sty.memberships)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__saMny
            )}
          >
            <Trans__>{"Memberships"}</Trans__>
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__jRXi
            )}
          >
            <Trans__>
              {
                "By purchasing a yoga membership from Halcyon Studios, you agree to abide by the terms outlined in these Terms and any additional terms provided to you at the time of purchase."
              }
            </Trans__>
          </div>
        </Stack__>
        <Stack__
          as={"div"}
          data-plasmic-name={"productsAndServices"}
          data-plasmic-override={overrides.productsAndServices}
          hasGap={true}
          className={classNames(projectcss.all, sty.productsAndServices)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__xlRee
            )}
          >
            <Trans__>{"Products and Services"}</Trans__>
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__unxB3
            )}
          >
            <Trans__>
              {
                "Halcyon Studios offers yoga memberships subject to availability. All products should be used strictly in accordance with any applicable instructions, precautions, and guidelines."
              }
            </Trans__>
          </div>
        </Stack__>
        <Stack__
          as={"div"}
          data-plasmic-name={"purchases"}
          data-plasmic-override={overrides.purchases}
          hasGap={true}
          className={classNames(projectcss.all, sty.purchases)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___6Wdo6
            )}
          >
            <Trans__>{"Purchases"}</Trans__>
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___2BlGn
            )}
          >
            <Trans__>
              {
                "Products, prices, and promotions are subject to change without notice. We reserve the right to suspend, update, or cancel any promotions at any time without notice. We strive to display accurate price information but may occasionally make errors, which we reserve the right to correct."
              }
            </Trans__>
          </div>
        </Stack__>
        <Stack__
          as={"div"}
          data-plasmic-name={"paymentTerms"}
          data-plasmic-override={overrides.paymentTerms}
          hasGap={true}
          className={classNames(projectcss.all, sty.paymentTerms)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__tOAtL
            )}
          >
            <Trans__>{"Payment Terms"}</Trans__>
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__gX6Jh
            )}
          >
            <Trans__>
              {
                "Payment for yoga memberships is due before acceptance of an order. By making a purchase, you represent that all information provided is true, correct, and complete."
              }
            </Trans__>
          </div>
        </Stack__>
        <Stack__
          as={"div"}
          data-plasmic-name={"paymentProcessing"}
          data-plasmic-override={overrides.paymentProcessing}
          hasGap={true}
          className={classNames(projectcss.all, sty.paymentProcessing)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__rhAjn
            )}
          >
            <Trans__>{"Payment Processing"}</Trans__>
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__yOiLd
            )}
          >
            <Trans__>
              {
                "Payment processing services for products purchased on the Site are provided by a third-party payment processor."
              }
            </Trans__>
          </div>
        </Stack__>
        <Stack__
          as={"div"}
          data-plasmic-name={"disclaimers"}
          data-plasmic-override={overrides.disclaimers}
          hasGap={true}
          className={classNames(projectcss.all, sty.disclaimers)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__aMq1
            )}
          >
            <Trans__>{"Disclaimers"}</Trans__>
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__qbyT
            )}
          >
            <Trans__>
              {
                "The information provided on the Site is for general informational purposes only and should not be considered medical or professional advice. Consult your physician before starting any exercise program."
              }
            </Trans__>
          </div>
        </Stack__>
        <Stack__
          as={"div"}
          data-plasmic-name={"limitationOfLiability"}
          data-plasmic-override={overrides.limitationOfLiability}
          hasGap={true}
          className={classNames(projectcss.all, sty.limitationOfLiability)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__cF5Pc
            )}
          >
            <Trans__>{"Limitation of Liability"}</Trans__>
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__sziAm
            )}
          >
            <Trans__>
              {
                "alcyon Studios shall not be liable for any damages resulting from your use of the Site or services provided. Our liability is limited to the extent permitted by law."
              }
            </Trans__>
          </div>
        </Stack__>
        <Stack__
          as={"div"}
          data-plasmic-name={"indemnification"}
          data-plasmic-override={overrides.indemnification}
          hasGap={true}
          className={classNames(projectcss.all, sty.indemnification)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___6HMk
            )}
          >
            <Trans__>{"Indemnification"}</Trans__>
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__kvqWg
            )}
          >
            <Trans__>
              {
                "You agree to indemnify and hold Halcyon Studios harmless from any claims arising out of your use of the Site or breach of these Terms."
              }
            </Trans__>
          </div>
        </Stack__>
        <Stack__
          as={"div"}
          data-plasmic-name={"forceMajure"}
          data-plasmic-override={overrides.forceMajure}
          hasGap={true}
          className={classNames(projectcss.all, sty.forceMajure)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__gudex
            )}
          >
            <Trans__>{"Force Majure"}</Trans__>
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__ztV7U
            )}
          >
            <Trans__>
              {
                "We will not be liable for any failure or delay in our performance under these Terms due to circumstances beyond our reasonable control."
              }
            </Trans__>
          </div>
        </Stack__>
        <Stack__
          as={"div"}
          data-plasmic-name={"governingLaw"}
          data-plasmic-override={overrides.governingLaw}
          hasGap={true}
          className={classNames(projectcss.all, sty.governingLaw)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___5Ys6K
            )}
          >
            <Trans__>{"Governing Law"}</Trans__>
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__or51T
            )}
          >
            <Trans__>
              {
                "These Terms shall be governed by and construed in accordance with the laws of the State of Florida, USA."
              }
            </Trans__>
          </div>
        </Stack__>
        <Stack__
          as={"div"}
          data-plasmic-name={"disputeResolution"}
          data-plasmic-override={overrides.disputeResolution}
          hasGap={true}
          className={classNames(projectcss.all, sty.disputeResolution)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__lsO88
            )}
          >
            <Trans__>{"Dispute Resolution"}</Trans__>
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__fxMT
            )}
          >
            <Trans__>
              {
                "Any disputes arising under these Terms shall be resolved through arbitration in Tampa, Florida, in accordance with the rules of the American Arbitration Association."
              }
            </Trans__>
          </div>
        </Stack__>
        <Stack__
          as={"div"}
          data-plasmic-name={"miscellaneous"}
          data-plasmic-override={overrides.miscellaneous}
          hasGap={true}
          className={classNames(projectcss.all, sty.miscellaneous)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__eoqmb
            )}
          >
            <Trans__>{"Miscellaneous"}</Trans__>
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__t3MIa
            )}
          >
            <Trans__>
              {
                "These Terms constitute the entire agreement between you and Halcyon Studios regarding your use of the Site. If any provision of these Terms is found to be invalid, the remaining provisions shall remain in full force and effect."
              }
            </Trans__>
          </div>
        </Stack__>
        <Stack__
          as={"div"}
          data-plasmic-name={"contactUs"}
          data-plasmic-override={overrides.contactUs}
          hasGap={true}
          className={classNames(projectcss.all, sty.contactUs)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__lJZvb
            )}
          >
            <Trans__>{"Contact Us"}</Trans__>
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__zpQsP
            )}
          >
            <Trans__>
              {
                "If you have any questions or concerns about these Terms, please contact us at admin@halcyonstudio.us."
              }
            </Trans__>
          </div>
        </Stack__>
      </section>
    </div>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "section",
    "introduction",
    "definitions",
    "useOfSite",
    "memberships",
    "productsAndServices",
    "purchases",
    "paymentTerms",
    "paymentProcessing",
    "disclaimers",
    "limitationOfLiability",
    "indemnification",
    "forceMajure",
    "governingLaw",
    "disputeResolution",
    "miscellaneous",
    "contactUs"
  ],

  section: [
    "section",
    "introduction",
    "definitions",
    "useOfSite",
    "memberships",
    "productsAndServices",
    "purchases",
    "paymentTerms",
    "paymentProcessing",
    "disclaimers",
    "limitationOfLiability",
    "indemnification",
    "forceMajure",
    "governingLaw",
    "disputeResolution",
    "miscellaneous",
    "contactUs"
  ],

  introduction: ["introduction"],
  definitions: ["definitions"],
  useOfSite: ["useOfSite"],
  memberships: ["memberships"],
  productsAndServices: ["productsAndServices"],
  purchases: ["purchases"],
  paymentTerms: ["paymentTerms"],
  paymentProcessing: ["paymentProcessing"],
  disclaimers: ["disclaimers"],
  limitationOfLiability: ["limitationOfLiability"],
  indemnification: ["indemnification"],
  forceMajure: ["forceMajure"],
  governingLaw: ["governingLaw"],
  disputeResolution: ["disputeResolution"],
  miscellaneous: ["miscellaneous"],
  contactUs: ["contactUs"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicContainerTermsOfService__ArgProps,
          internalVariantPropNames: PlasmicContainerTermsOfService__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicContainerTermsOfService__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicContainerTermsOfService";
  } else {
    func.displayName = `PlasmicContainerTermsOfService.${nodeName}`;
  }
  return func;
}

export const PlasmicContainerTermsOfService = Object.assign(
  // Top-level PlasmicContainerTermsOfService renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    section: makeNodeComponent("section"),
    introduction: makeNodeComponent("introduction"),
    definitions: makeNodeComponent("definitions"),
    useOfSite: makeNodeComponent("useOfSite"),
    memberships: makeNodeComponent("memberships"),
    productsAndServices: makeNodeComponent("productsAndServices"),
    purchases: makeNodeComponent("purchases"),
    paymentTerms: makeNodeComponent("paymentTerms"),
    paymentProcessing: makeNodeComponent("paymentProcessing"),
    disclaimers: makeNodeComponent("disclaimers"),
    limitationOfLiability: makeNodeComponent("limitationOfLiability"),
    indemnification: makeNodeComponent("indemnification"),
    forceMajure: makeNodeComponent("forceMajure"),
    governingLaw: makeNodeComponent("governingLaw"),
    disputeResolution: makeNodeComponent("disputeResolution"),
    miscellaneous: makeNodeComponent("miscellaneous"),
    contactUs: makeNodeComponent("contactUs"),
    // Metadata about props expected for PlasmicContainerTermsOfService
    internalVariantProps: PlasmicContainerTermsOfService__VariantProps,
    internalArgProps: PlasmicContainerTermsOfService__ArgProps
  }
);

export default PlasmicContainerTermsOfService;
/* prettier-ignore-end */
