// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2p9VhVhxAWhB5Nusx9QUQ2
// Component: Te9KU2ZufSm0
import * as React from "react";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  renderPlasmicSlot,
  useCurrentUser,
  usePlasmicTranslator
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 2p9VhVhxAWhB5Nusx9QUQ2/projectcss
import sty from "./PlasmicMarianaTekBuyComponent.module.css"; // plasmic-import: Te9KU2ZufSm0/css

createPlasmicElementProxy;

export const PlasmicMarianaTekBuyComponent__VariantProps = new Array();

export const PlasmicMarianaTekBuyComponent__ArgProps = new Array(
  "marianaTekBuySlot"
);

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicMarianaTekBuyComponent__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $translator = usePlasmicTranslator?.();
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  return (
    <section
      data-plasmic-name={"marianaTek"}
      data-plasmic-override={overrides.marianaTek}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.marianaTek
      )}
    >
      {renderPlasmicSlot({
        defaultContents: null,
        value: args.marianaTekBuySlot
      })}
      <Embed
        data-plasmic-name={"embedHtml"}
        data-plasmic-override={overrides.embedHtml}
        className={classNames("__wab_instance", sty.embedHtml)}
        code={'<div data-mariana-integrations="/buy"></div>'}
      />
    </section>
  );
}

const PlasmicDescendants = {
  marianaTek: ["marianaTek", "embedHtml"],
  embedHtml: ["embedHtml"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMarianaTekBuyComponent__ArgProps,
          internalVariantPropNames: PlasmicMarianaTekBuyComponent__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMarianaTekBuyComponent__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "marianaTek") {
    func.displayName = "PlasmicMarianaTekBuyComponent";
  } else {
    func.displayName = `PlasmicMarianaTekBuyComponent.${nodeName}`;
  }
  return func;
}

export const PlasmicMarianaTekBuyComponent = Object.assign(
  // Top-level PlasmicMarianaTekBuyComponent renders the root element
  makeNodeComponent("marianaTek"),
  {
    // Helper components rendering sub-elements
    embedHtml: makeNodeComponent("embedHtml"),
    // Metadata about props expected for PlasmicMarianaTekBuyComponent
    internalVariantProps: PlasmicMarianaTekBuyComponent__VariantProps,
    internalArgProps: PlasmicMarianaTekBuyComponent__ArgProps
  }
);

export default PlasmicMarianaTekBuyComponent;
/* prettier-ignore-end */
